# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=2000)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
    ]
